<?php

/**
 * @file
 * Module file for recently_viewed.
 */

/**
 * Implements hook_block_info().
 */
function things_recently_viewed_block_info() {

  $block = array();

  $block['things_recently_viewed'] = array(
    'info' => t('Shows recently viewed blocks'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $block;
}

/**
 * Implements hook_block_view().
 */
function things_recently_viewed_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'things_recently_viewed':
      $block['subject'] = t('Recently Viewed');
      $block['content'] = things_recently_viewed_efq();
      break;

    default:
      '';
  }
  return $block;
}

// Grab our user activity.
function things_recently_viewed_efq() {
  drupal_add_js(drupal_get_path('module', 'things_recently_viewed') . '/assets/quickpager.jquery.js');
  drupal_add_js(drupal_get_path('module', 'things_recently_viewed') . '/assets/pager.js');
  drupal_add_css(drupal_get_path('module', 'things_recently_viewed') . '/assets/things_recently_viewed.css');
  global $user;

  $uid = $user->uid;
  $query = db_select('node', 'n');
  $query->join('history', 'h', 'n.nid = h.nid AND h.uid = :uid', array(':uid' => $uid));
  $query->orderby('timestamp', 'DESC')
        ->fields('n', array('nid', 'title'))
        ->fields('h', array('timestamp'))
        ->range(0, 50);
  $results = $query->execute()->fetchall();

  $output = '';
  if (!empty($results)) {

    $output .= '<ul id="things-recently-viewed-items" class="paging">';

    foreach ($results as $item) {
      $output .= '<li class="things-recently-viewed-items-li">' . l($item->title, 'node/' . $item->nid) . ' - ' . date('Y-m-d H:i:s', $item->timestamp) . '</li>';
    }
    $output .= '</ul>';
  }

  return $output;
}
